import React from 'react';
import { Image, ImageStyle, StyleProp } from 'react-native';
import { layout } from '@/theme';

// Generated by scripts/generate-logo.mjs together with the app icons.
const source = require('../../../assets/logo.png');

type Props = {
  size?: number;
  style?: StyleProp<ImageStyle>;
};

export function Logo({ size = layout.minTouch, style }: Props) {
  return (
    <Image
      source={source}
      style={[{ width: size, height: size }, style]}
      accessibilityRole="image"
      accessibilityLabel="DSS Wearables logo"
    />
  );
}
